### ISSUE TITLE
it doesn't support absolute path import

### ISSUE THREAD

**Issue by yidongw** [Js-Brecht/gatsby-plugin-ts-config#34] opened 2021-05-23 16:25 UTC
I added a plugin `gatsby-plugin-root-import` into plugins in `gatsby-config.js` file like the following.
```
    {
      resolve: "gatsby-plugin-root-import",
      options: {
        src: path.join(__dirname, "src"),
      },
    },
```
yet it doesn't seem to be working when I import files using the absolute path in `gatsby-node.ts`

**Comment by Js-Brecht** [comment] 2021-05-25 18:57
`gatsby-plugin-root-import` is for a Webpack plugin.  Webpack does not process `gatsby-node`.

**Comment by Js-Brecht** [comment] 2021-05-25 18:59
@yidongw this plugin automatically sets up support for using aliases from `tsconfig.json`, however.  You just have to set up `baseUrl` and `paths`, then use them in your imports.

https://www.typescriptlang.org/docs/handbook/module-resolution.html#additional-module-resolution-flags

**Comment by Js-Brecht** [comment] 2021-06-01 22:34
@yidongw did that solve the problem?

**Comment by yidongw** [comment] 2021-06-30 10:54
sorry I was busy. @Js-Brecht 
No. I have tsconfig setup like this
```
{
  "compilerOptions": {
    "target": "es5",
    "downlevelIteration": true,
    "module": "commonjs",
    "jsx": "preserve",
    "strict": true,
    "baseUrl": "./",
    "paths": {
      "src/*": ["src/*"],
      "abi/*": ["abi/*"],
      "types/*": ["types/*"]
    },
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  },
  "include": ["src/custom.d.ts", "src/**/*", "gatsby/**/*", "__mocks__/**/*"]
}
```

It will throw an error
```
 Error: [gatsby-plugin-ts-config] An error occurred while reading your gatsby-node!
  Cannot find module 'abi/*.json'
```

**Comment by Js-Brecht** [comment] 2021-06-30 16:55
What is `abi/*.json`?  Can you show me the code that tries to import that?

**Comment by yidongw** [comment] 2021-07-01 02:11
`abi/*.json` is just a json file, nothing special.

`src` alias is not working either.

In my `gatsby-node.ts` file, if I change relative import to `import MainModel from "src/stores/MainStore"`, it will throw an error during `build` or `develop`

Here is the full error message
```
  Error: [gatsby-plugin-ts-config] An error occurred while reading your gatsby-node!
  Cannot find module 'src/stores/MainStore'
  Require stack:
  - /Users/alanwang/project/gatsby/gatsby-node.ts
  - /Users/alanwang/project/node_modules/gatsby-plugin-ts-config/dist/utils/node.js
  - /Users/alanwang/project/node_modules/gatsby-plugin-ts-config/dist/utils/endpoints.js
  - /Users/alanwang/project/node_modules/gatsby-plugin-ts-config/dist/gatsby/gatsby-config.js
  - /Users/alanwang/project/node_modules/gatsby-plugin-ts-config/gatsby-config.js
  - /Users/alanwang/project/node_modules/gatsby/dist/bootstrap/get-config-file.js
  - /Users/alanwang/project/node_modules/gatsby/dist/bootstrap/load-themes/index.js
  - /Users/alanwang/project/node_modules/gatsby/dist/services/initialize.js
  - /Users/alanwang/project/node_modules/gatsby/dist/services/index.js
  - /Users/alanwang/project/node_modules/gatsby/dist/bootstrap/index.js
  - /Users/alanwang/project/node_modules/gatsby/dist/commands/build.js
  - /Users/alanwang/project/node_modules/gatsby/node_modules/gatsby-cli/lib/create-cli.js
  - /Users/alanwang/project/node_modules/gatsby/node_modules/gatsby-cli/lib/index.js
  - /Users/alanwang/project/node_modules/gatsby/dist/bin/gatsby.js
  - /Users/alanwang/project/node_modules/gatsby/cli.js

  - loader.js:965 Function.Module._resolveFilename
    internal/modules/cjs/loader.js:965:15

  - loader.js:841 Function.Module._load
    internal/modules/cjs/loader.js:841:27

  - loader.js:1025 Module.require
    internal/modules/cjs/loader.js:1025:19

  - v8-compile-cache.js:159 require
    [project]/[v8-compile-cache]/v8-compile-cache.js:159:20

  - gatsby-node.ts:8 Object.<anonymous>
    /Users/alanwang/project/gatsby/gatsby-node.ts:8:41

  - v8-compile-cache.js:192 Module._compile
    [project]/[v8-compile-cache]/v8-compile-cache.js:192:30

  - index.js:99 Module._compile
    [project]/[pirates]/lib/index.js:99:24

  - loader.js:1157 Module._extensions..js
    internal/modules/cjs/loader.js:1157:10

  - index.js:104 Object.newLoader [as .ts]
    [project]/[pirates]/lib/index.js:104:7

  - loader.js:985 Module.load
    internal/modules/cjs/loader.js:985:32

  - loader.js:878 Function.Module._load
    internal/modules/cjs/loader.js:878:14

  - loader.js:1025 Module.require
    internal/modules/cjs/loader.js:1025:19

  - v8-compile-cache.js:159 require
    [project]/[v8-compile-cache]/v8-compile-cache.js:159:20

  - node.js:21 Object.exports.tryRequireModule
    [project]/[gatsby-plugin-ts-config]/dist/utils/node.js:21:44

  - gatsby-config.js:94 theme
    [project]/[gatsby-plugin-ts-config]/dist/gatsby/gatsby-config.js:94:35

  - index.js:67 resolveTheme
    [project]/[gatsby]/src/bootstrap/load-themes/index.js:67:19


not finished open and validate gatsby-configs - 1.813s

```

**Comment by Js-Brecht** [comment] 2021-07-01 02:19
Can you share the project, or a reproduction?

**Comment by Js-Brecht** [comment] 2021-08-15 09:04
@yidongw did you ever make any progress on this?

**Comment by Js-Brecht** [comment] 2021-09-03 17:13
I’m going to close this, since it seems to be abandoned.

@yidongw  if there is issue persists, feel free to comment again, and I can reopen

**Closed by Js-Brecht** 2021-09-03 17:13 UTC
