### ISSUE TITLE
When using yarn workspaces and gatsby-themes, there is an infinite loop on "open and validate gatsby-configs"

### ISSUE THREAD

**Issue by Everspace** [Js-Brecht/gatsby-plugin-ts-config#20] opened 2020-11-19 06:58 UTC
I have a workspace like so:

```json
//workspace package.json
{
  "workspaces": [
    "gatsby-theme-project-core",
    "gatsby-theme-project-uses-core",
    "my-site"
  ],
  "resolutions": {
    "gatsby-theme-project-core": "*",
    "gatsby-theme-project-using-core": "*"
  }
}
```
both `project-core` and `project-uses-core` have a `gatsby-config.js` of
```js
const tsconfig = require("gatsby-plugin-ts-config")

module.exports = tsconfig.generateConfig({
  configDir: ".gatsby",
  projectRoot: __dirname,
})
```
my-site does not use `gatsby-plugin-ts-config`, and uses a more normal `gatsby-config.js` of just requiring the two above. It's purpose is to only hold content.

And when I go to run `yarn workspace my-site run build` locally after a clean, I get an "open and validate gatsby-configs" that lasts forever.

**Comment by Js-Brecht** [comment] 2020-11-20 03:46
Hello @Everspace,

I can't actually say I'm surprised.  `gatsby-plugin-ts-config` wasn't really designed with multiple runtime instances in mind.  The thought had crossed my mind to support multiple declarations in different themes, but instead decided to rely on Gatsby's plugin deduplication and the assumption that most plugins and themes are generally used as installed modules, so their structure/format would follow the common Gatsby standard.

Gatsby's deduplication process would normally have removed the duplicate `gatsby-plugin-ts-config` plugin, favoring the one that appears first in the plugin tree.  However, your use of `__dirname` means the plugin options are dynamic, which tells Gatsby that it should keep both instances.

This is a rather interesting use case.  I assume you have Typescript gatsby configs in both themes, and you would like each theme treated separately, each able to transpile its own configs.  There's a few problems with this that I can think of off the top of my head, with regards to the current design:

1. We cannot feasibly run multiple `ts-node` or `babel-register` instances in a single node thread.  Both of those libraries overload `require.extensions`, which allows them to transpile modules as they are read, instead of needing to build them ahead of time.  This means that if they are initialized more than once, they will wrap each other.  This is one of the things that's happening in your setup, and I can only imagine what kind of havoc it is causing.

2. Because `gatsby-plugin-ts-config` must share options, configurations, and methods between the various stages of the Gatsby lifecycle, and Gatsby itself doesn't expose a method for doing this, I opted for singletons that are then shared between modules.  This isn't necessarily a blocker, I don't think, but it does mean that data that is passed to any of the theme's endpoints will not be definitively the data that belongs to that theme.  There's a good chance that some of the data will belong to a different theme, whichever one(s) ran before.

3. `gatsby-plugin-ts-config` makes use of Webpack aliases in order to direct Gatsby's webpack process to the correct `gatsby-browser` and/or `gatsby-ssr` files.  If this is being called multiple times, one will override the other, meaning one of the theme's runtime endpoints won't be called.  I guarantee that this will result in some undesired behavior, if those files are being used.

4. Because the Typescript config files are usually kept in a different folder than Gatsby is expecting them, `gatsby-plugin-ts-config` has to provide its own `gatsby-*` modules, which it uses to create a sort of proxy that points Gatsby to the _actual_, newly transpiled modules.  Because you are working with Yarn workspaces, both themes are using the same module instance of `gatsby-plugin-ts-config`, and because this proxy happens at the module level (as opposed to inside a function), there's not really a good way to tell it which theme instance to proxy to.

1 could be fixed fairly easily.

2 and 3 would be a bit more difficult, but still possible.  It would probably require a sort of registry that will track the needed instances for each different theme.

4 is... going to take some thought.  I can't think of a good way to solve it at the moment.  When Gatsby reads `gatsby-config` files, it would be fairly easy to distinguish between different themes because Gatsby will call the `gatsby-config` function for each theme.  However, the `gatsby-node` setup in this plugin happens when the module is first read, so most everything happens at the module level.  This means it won't be processed again when Gatsby attempts to read it a second time; only the cached module would be returned... it would essentially be giving each theme the same endpoints.

I will think on it.  It may require reworking the entire method that this plugin uses.

In the meantime, I would appreciate it if you could share a minimal reproduction.  It will make testing/debugging much easier

**Comment by Everspace** [comment] 2020-11-20 05:08
> I assume you have Typescript gatsby configs in both themes, and you would like each theme treated separately, each able to transpile its own configs.

You are correct. Although more specifically, I use it for `gatsby-node` primarily. Writing with it and graphqlgen, both had made my life a lot easier and I found the development experience to be pleasant on a toy blog I was fiddling with. I had attempted to port it to a more complex thing where the typescript has frankly gotten out of hand with workarounds, and this seemed like a natural fit. 

I expected it to be essentially a super-pickle since there's a lot of interesting things happening in the background that I'm not really sure about. Before, I had been doing... `require('ts-node').register`? or something like that but this causes other problems that make it hard to work with for other reasons. This gets trickier and trickier since themes can depend on other themes.

Here is a minimal repoduction that should be set up for a simple `yarn && yarn build` to see the loop: https://github.com/Everspace/gatsby-plugin-ts-config-issue-20

**Comment by Js-Brecht** [comment] 2020-11-25 00:45
@Everspace the only way I can think of to make this work correctly is to not use the module proxy, which is required in order to be able to put your `gatsby-*` files in a different directory... and that's required so that Gatsby won't try to process your `gatsby-config` or `gatsby-node` twice.  Reading the modules twice is really only an issue for `gatsby-node` right now because it will try to run the endpoints in the context of `gatsby-plugin-ts-config`, and then again in the context of the consumer.  Not only will this cause the endpoints to run twice (not usually desired)... it will also cause node ownership conflicts.

The node ownership conflicts would be resolved by my planned solution for #18... but this actually brings to mind additional issues that would be encountered by the way I wanted to solve #18.  Mainly the fact that your primary site's name is `default-site-plugin`, while the themes would have to use the name from their `package.json`.  That's an issue for another day, however.

Essentially what I would have to do for all of this to work properly is turn off the module proxy, so that `gatsby-plugin-ts-config/gatsby-*.js` doesn't point to the consumer's `gatsby-*`.  This means `gatsby-plugin-ts-config` could still transpile the consumer's `gatsby-*` files so they can be read successfully from the `require` cache, but that would basically be it.
* When using a single instance of the plugin, this also means _**none**_ of the consumers would be able to use a subdirectory to store their `gatsby-*` files.  Once the proxy is read for one, it's read for all.  Not necessarily a problem... once the node ownership/duplicate api calls is resolved, using a subdirectory will only be a convenience.
* This also means that the other ways you can use this plugin will be disabled, namely the default export function + property bag... also not a blocker, just a caveat to that run type.

I'm curious: have you tried turning off hoisting for `gatsby-plugin-ts-config`?  If it were stored in the `node_modules` for each theme, the themes wouldn't be using the same instances, which I think might be a decent workaround for now.

---

I apologize, I haven't had time to run your reproduction, or had _any_ time to put into this yet.  I am so busy these days that I don't often have time to work on this plugin.  I'm hoping that with the holidays coming up, I will have some time I can set aside for this issue.

**Comment by Everspace** [comment] 2020-11-25 05:47
No worries here for whenever/if this happens. I am mostly annoyed that gatsby has "first class" typescript support except where (in my mind) it actually matters (the node API).

Hoisting enabled/or/not I'm not sure is relevant, since the goal would be say, publishing a package that just uses gatsby-plugin-ts-config, and then this would cause a duplication in the `node_modules` anyway.

You could do something zany like compile the individual `ts` files, and then require the resultant files within the cache you place them in. You could do something like a hash of the file-paths provided so that different modules are written to unique paths.

**Comment by Js-Brecht** [comment] 2020-11-25 07:02
I would assume that most published packages would be transpiled ahead of time.  There are cases of people using this plugin in a theme, and that has worked out pretty well; but they also were adding Typescript support for the default site, not the theme itself.  In that sort of use case (adding support for the default site), multiple entries of this plugin would usually get stripped out by Gatsby’s deduplication process.

You do make a good point about transpiling ahead of time.  At the beginning, I had intended on including an ahead of time compiling option, as opposed to the JIT.  That wound up getting (mostly) scrapped because it started to turn into another bundler... but you’ve given me an idea for a couple more things I can try:

1. This plugin is basically a theme of its own, and it already makes heavy use of the require cache.  Instead of trying to serve up the configured `gatsby-*` modules as its own, it could instead pass back a plugin config to Gatsby pointing to the desired config files as if they’re plugins themselves.  Since it will have already read the files, they will already be transpiled and will exist as objects in the require cache, so Gatsby should be able to pick them up without any issue 🤔.  This does move the desired `gatsby-*` files another layer deeper, and could very well cause more unforeseen issues, but it has potential.
    * This is very similar to what the `includePlugins` api from this plugin does.  It supports transpiling `gatsby-*` files inside of additional plugins, to include local plugins.

2. Another option that just dawned on me is to wrap each set of `gatsby-*` files using a queue so that it can operate in layers.  It already wraps the desired `gatsby-*` files... would just need to make it call the endpoints in sequence, much like Gatsby itself does 

What’s amusing about this is that I keep winding up duplicating some of the core functions from Gatsby.
* Both of these options will need to implement Gatsby’s plugin deduplication process, otherwise there could be inconsistencies between a theme’s `gatsby-config` (which could be dumped in certain instances because of deduplication), and its `gatsby-node` (which would wind up included by this plugin regardless).
* The second option would be like creating shadow node/ssr/browser api runners, which are the modules Gatsby uses to run `gatsby-node` and the `gatsby-ssr`/`gatsby-browser` apis, respectively.
* Both options will require configuring node ownership.

It’s been suggested by a member of the Gatsby team that this work be done in the core instead... which would simplify things, tbh.  I would just have to compromise on some key points, however, so I haven’t been very motivated to put the time into it.

**Comment by Everspace** [comment] 2020-11-25 07:39
It would be nice if this ts support was in core somehow, but I won't begrudge anyone what they do in their spare time. If you find out you're repeating some things, perhaps you can redo or borrow some work already done for you.

This is beyond my own ability at the moment so I'll happily rubber-duck.

**Closed** 2021-08-15 08:42 UTC
