### ISSUE TITLE
Cannot find module defined in paths

### ISSUE THREAD

**Issue by ptrhck** [Js-Brecht/gatsby-plugin-ts-config#5] opened 2020-03-17 11:56 UTC
I initially installed [this ](https://www.gatsbyjs.org/packages/gatsby-plugin-tsconfig-paths/) plugin in order to load packages of my monorepo as described [here](https://www.gatsbyjs.org/blog/2019-01-01-publish-multiple-gatsby-sites/). It works just fine with the mentioned plugin to import them in my typescript files.

Then, another use case occured. I also wanted to load a variable from one of the packages in my `gatsby-config.js` like so: `const { global } = require('@shared-ui/design');`. The module was not found, so I thought this plugin might help.

I have moved all new ts files to the `.gatsby` folder and used your example [babel configuration](https://github.com/Js-Brecht/gatsby-plugin-ts-config#babel-example-usage). The following error arises:

```
Error: [gatsby-plugin-ts-config] An error occurred while reading your gatsby-config!
  Cannot find module @shared-ui/design'
```

Is this setup supposed to work or am I missing something? Note that the gatsby tsconfig extends from my root tsconfig, where the paths are defined. In my gatsby application I do not have a babelconfig yet.

Many thanks!

**Comment by Js-Brecht** [comment] 2020-03-17 16:13
Hi @ptrhck, thanks for filing this issue!

If `@shared-ui/design` exists in your `node_modules`, then the standard node resolution should work.  Since you mention using `gatsby-plugin-tsconfig-paths`, and the example babel configuration, is it safe to assume that `@shared-ui/design` is an alias?

> In my gatsby application I do not have a babelconfig yet.

You shouldn't need one, TBH.  Gatsby sets up its own babel configuration under the hood to process your site, and this plugin does the same when processing your config files.

Can you share your repo, or a simplified reproduction?  Might make it easier to pinpoint the issue

**Comment by Js-Brecht** [comment] 2020-03-17 16:31
Sorry, I didn't read the post title closely the first time.

Can you share what your `paths` looks like from your `tsconfig`?

**Comment by ptrhck** [comment] 2020-03-17 16:34
Here we go:

```
{
  "compilerOptions": {
    "target": "esnext",
    "module": "commonjs",
    "lib": ["dom", "esnext"],
    "jsx": "react",
    "strict": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "noEmit": true,
    "skipLibCheck": true,
    "baseUrl": "./",
    "paths": {
      "@shared-ui/*": [
        "shared-ui/*/src"
      ]
    },
    "typeRoots": ["custom_typings" ,"node_modules/@types"]
  },
  "exclude": ["node_modules", "shared-ui/**/node_modules"]
}
```

**Comment by Js-Brecht** [comment] 2020-03-17 17:27
`babel-plugin-module-resolver` is not very compatible with all of the use cases presented by `compilerOptions.paths`.

One thing that it probably wouldn't do correctly with your setup is determine the correct `baseUrl`.  I'm assuming that "very root" means the top of your monorepo.  In that case, using this line:
```js
    moduleResolverOpts.root = [path.resolve(__dirname, tsconfig.compilerOptions.baseUrl)];
```
won't work very well, because it is only going to make it look in the directory of your project, not the monorepo root.  It's not going to intelligently determine what `baseUrl` points to, unless you update that line to also point to root directory.

However, `babel-plugin-module-resolver` doesn't even use the `root` property the same way Typescript uses `baseUrl`.  Typescript basically prepends the `baseUrl` to the aliased path.  `babel-plugin-module-resolver` runs a two-fold resolution... it tries to resolve against the `alias` properties first, then it tries to resolve against the `root`.  What this means for you is that even if you did set up the `root` property to point to your monorepo root, it still won't replace `@shared-ui/*` with `<root>/shared-ui/*/src`, because of how the `root` resolution does no replacements.  It just wants the `@shared-ui/design` module to be relative to the root.  With a structure like this:
```text
monorepo
  ├── shared-ui
  │   └── design
  └── project
      └── gatsby-config.js
```
I could make the `root` property look like `[path.dirname(__dirname)]`, and it would find the correct source module _**if**_ my imported module module reads
```js
import Foo from 'shared-ui/design/src'.
```

`babel-plugin-module-resolver` also doesn't support wildcards 😕.  It doesn't know that it needs to replace the wildcard in `shared-ui/*/src` with the value resolved from the wildcard in `@shared-ui/*`.  What you **could** do is include an array of values for the `alias` property, but it's going to be labor intensive to make it feature complete.

---

What I've been wanting to do for a while is write my own babel plugin that will be compatible with the aliases you are able to use in `tsconfig.json`, because it would make things much simpler.

All that being said, I think it might be easier for you to use [ts-node](https://github.com/Js-Brecht/gatsby-plugin-ts-config#ts-node-example-usage), since it uses Typescript itself to resolve your aliases, so it should be 100% compatible with your `tsconfig`.

If your `gatsby-config` is a `.js` file, it should still be able to read it because `ts-node` is configured automatically to [allow javascript](https://github.com/Js-Brecht/gatsby-plugin-ts-config/blob/master/src/utils/options-handler.ts#L54).

However, it might even be more beneficial to move to `.ts` files all the way around, because then you can also use type inference & checking.  Check out [the examples](https://github.com/Js-Brecht/gatsby-plugin-ts-config#examples) for writing `gatsby-config` and `gatsby-node` in Typescript 🙂

**Comment by Js-Brecht** [comment] 2020-03-17 17:40
Updated my last response to show the usage in CommonJS, too.

**Comment by ptrhck** [comment] 2020-03-17 17:41
Thank you for your great answer!

What I was wondering in the first place:

The package `@shared-ui/design` is a dependecy in the gatsby app. As the monorepo is managed with lerna, to my understanding, the import should work just fine in the `gatsby-config.js` or any other `src/*.tsx` file. Would you agree?

I solved the issue that it could not be import it in the tsx files with your other plugin `gatsby-plugin-tsconfig-paths`. It works, however, I am not sure if it should not just work if lerna manages everything right?

Then I thought, oh okay, that works but as the plugin is loaded in the same file where I would also like to import something from the other package, I thought this cannot work. So I installed this plugin to add paths handling even to the gatsby config file.

**Comment by Js-Brecht** [comment] 2020-03-17 18:14
> The package `@shared-ui/design` is a dependecy in the gatsby app. As the monorepo is managed with lerna, to my understanding, the import should work just fine in the `gatsby-config.js` or any other `src/*.tsx` file. Would you agree?

Oh, I see.  I do agree, but that would require that the dependency be in production form.  I.e. it would require the `@shared-ui/design` project to be built, and the `(package.json).main` or `(package.json).exports` to be pointing to the correct location, as if you were getting ready to publish it.  If it is configured & built, then you don't need the alias that points to the `src` directory.

> It works, however, I am not sure if it should not just work if lerna manages everything right?

Lerna will create symlinks for workspace dependencies in the project's `node_modules` that point to the local directory containing that dependency.  This works, but since it uses node's resolution, it requires that the package be set up to tell Node where to look for the source.

If you don't want to build your `@shared-ui/design` project, but use the files from `src` directly, you should be able to make its `package.json` include something like this:
```json
{
  "main": "./src/index.ts"
}
```
Then, when you import `@shared-ui/design`, node will find the symlink in `node_modules`, look in `package.json`, see `main`, and go import the file it points to.  As long as whatever is importing it knows how to read Typescript, you're good!

However, if you ever want to import a different file other than `./src/index.ts`, you will need to include the full path, relative to that project (e.g. `@shared-ui/design/src/foo`), **OR** you can include the [`exports` property in `package.json`](https://nodejs.org/dist/latest-v12.x/docs/api/esm.html#esm_package_exports) to let node know about the other files you're exporting.

**Comment by Js-Brecht** [comment] 2020-03-18 17:57
@ptrhck did that work for you?

**Comment by ptrhck** [comment] 2020-03-19 08:26
Yes, I have fixed the `main `entry in my `package.json` and used your [ts-node](https://github.com/Js-Brecht/gatsby-plugin-ts-config#ts-node-example-usage) example. Thank you!

**Comment by Js-Brecht** [comment] 2020-03-19 15:48
Glad to hear!  I'm going to go ahead and close this issue, but if you have anymore questions, feel free to comment.

**Closed by Js-Brecht** 2020-03-19 15:48 UTC
