### ISSUE TITLE
Allow ES6 modules

### ISSUE THREAD

**Issue by flogy** [Js-Brecht/gatsby-plugin-ts-config#8] opened 2020-04-21 07:42 UTC
Hi there,

First of all: thanks for this great library! Seems to be really underappreciated. Hope it will get more stars soon 🙂

**Problem description:**

I have a problem with an ES6 module dependency though. I am not 100% sure if it is related to this library but the name is mentioned in the error output, so it might be the case.

The dependency I use is [capacitor-fcm](https://github.com/stewwan/capacitor-fcm).

**Possible solution?**

I found a Gatsby plugin ([gatsby-plugin-compile-es6-packages](https://github.com/robwalkerco/gatsby-plugin-compile-es6-packages)) that should solve this problem, but it seems not to be working together with gatsby-plugin-ts-config.

**Error log:**
```
 ERROR 

[gatsby-plugin-ts-config] An error occurred while reading your gatsby-config!
Unexpected token export



  Error: C:\Users\flogy\Documents\Development\my-app\node_modules\capacitor-fcm\dist\esm\index.js:1
  (function (exports, require, module, __filename, __dirname) { export * from "./plugin";
                                                                ^^^^^^
  SyntaxError: Unexpected token export

  - v8-compile-cache.js:226 NativeCompileCache._moduleCompile
    [my-app]/[v8-compile-cache]/v8-compile-cache.js:226:18

  - v8-compile-cache.js:172 Module._compile
    [my-app]/[v8-compile-cache]/v8-compile-cache.js:172:36

  - index.js:99 Module._compile
    [my-app]/[pirates]/lib/index.js:99:24

  - loader.js:789 Module._extensions..js
    internal/modules/cjs/loader.js:789:10

  - index.js:104 Object.newLoader [as .js]
    [my-app]/[pirates]/lib/index.js:104:7

  - loader.js:653 Module.load
    internal/modules/cjs/loader.js:653:32

  - loader.js:593 tryModuleLoad
    internal/modules/cjs/loader.js:593:12

  - loader.js:585 Function.Module._load
    internal/modules/cjs/loader.js:585:3

  - loader.js:692 Module.require
    internal/modules/cjs/loader.js:692:17

  - v8-compile-cache.js:159 require
    [my-app]/[v8-compile-cache]/v8-compile-cache.js:159:20

  - CapacitorStore.ts:14 Object.<anonymous>
    C:/Users/flogy/Documents/Development/my-app/src/Stores/CapacitorStore.ts:14:21

  - v8-compile-cache.js:178 Module._compile
    [my-app]/[v8-compile-cache]/v8-compile-cache.js:178:30

  - index.js:99 Module._compile
    [my-app]/[pirates]/lib/index.js:99:24

  - loader.js:789 Module._extensions..js
    internal/modules/cjs/loader.js:789:10

  - index.js:104 Object.newLoader [as .ts]
    [my-app]/[pirates]/lib/index.js:104:7


not finished open and validate gatsby-configs - 1.124s
```

Do you see any way to get this work? Thanks in advance!

**Comment by Js-Brecht** [comment] 2020-04-21 19:50
Are you importing `capacitor-fcm` in your `gatsby-config`?  That should be the only reason it throws that error.

`gatsby-plugin-ts-config` only transpiles files that are in your project directory; it ignores everything inside of `node_modules`, which would explain why it is not able to read that file.  **but**, it looks like that is not a library that should be used during bootstrap.

It would be possible to expose a hook from `gatsby-plugin-ts-config`, to allow you to define what gets ignored and what doesn't.

Are you able to share your repository, or explain how you're using it?  It would help me figure out what needs to happen.

**Comment by Js-Brecht** [comment] 2020-04-21 20:21
> First of all: thanks for this great library! Seems to be really underappreciated. Hope it will get more stars soon 🙂

Thank you for the kind words, btw 🙂.  I suppose the desire to use Typescript in `gatsby-config` and `gatsby-node` is not very prevalent yet, or people just don't know that it's possible with this plugin.  This plugin will become obsolete eventually anyway, when Gatsby implements this functionality into the core.  If I had the time I'd do that myself, but I'd want to do more to alter the build process than just transpiling the modules, so it would be one of those things that should probably go through the RFC channel, and would likely take more time than I want to put into it.

**Comment by flogy** [comment] 2020-04-22 13:42
I am not importing it directly to my `gatsby-config` but I am wrapping the root element with a context provider which imports `capacitor-fcm` (`wrapRootElement` hook of `gatsby-ssr.ts` and `gatsby-browser.ts`). When commenting out the library import it works.

Having an option to ignore certain dependencies would be great! I have tried the [gatsby-plugin-browser-dependencies](https://www.gatsbyjs.org/packages/gatsby-plugin-browser-dependencies/) plugin which modifies the webpack configuration but without success.

I also took a quick look at the code of this repository but I could not figure out where the transpilation happens / where the problem occurs exactly.

Unfortunately, I can't provide you direct access to the project as it is a private repository (client work). If needed I could create a sample project though.

Hope we can find a solution together 🙂 Let me know where I can assist! Thank you.

**Comment by Js-Brecht** [comment] 2020-04-22 16:51
Transpilation by this plugin is done using `@babel/register` or `ts-node`, and those are set up in [this module](https://github.com/Js-Brecht/gatsby-plugin-ts-config/blob/master/src/utils/register.ts).  I went with those because they are able to do in-place transpilation; handling the transpilation of the modules myself, including the traversal that needs to happen, felt like rebuilding a bundler, so it didn't really seem like it was worth the time.

Probably don't want to use `gatsby-plugin-browser-dependencies` since it actually turns **off** the Webpack loaders for specific modules.  The first one you mentioned, `gatsby-plugin-compile-es6-packages` should really work for what you're doing.  However, you shouldn't even really _need_ to do that.  Gatsby will bundle up packages from `node_modules` already, and it should pass them all through `babel-loader`.  It's entirely possible that I'm forgetting some setting, though.

I was thinking that it may have to do with the combination of CommonJS and ESM... but I think that has more to do with importing in an ES module from a CJS one.  If importing in ESM from CJS, you're only supposed to import the default export (or namespace, I believe).  There may wind up being issues along that line because this plugin uses a "proxy", of sorts, to proxy requests from **its** `gatsby-browser`/`gatsby-ssr` to yours... and that proxy is CJS.  You could bypass that stage altogether by putting `gatsby-browser` and `gatsby-ssr` in the root of your project, next to `gatsby-config.js`.

However, it still seems really strange to me that it is throwing the error in `gatsby-config`.  The place that call happens is [here](https://github.com/Js-Brecht/gatsby-plugin-ts-config/blob/master/src/gatsby/gatsby-config.ts#L85), and all of that happens before Gatsby finishes the `open and validate gatsby-configs` stage, which is where it looks like the error is happening.  That **specific** error, where it mentions `gatsby-config`, should only ever happen when executing the `tryRequireModule()` **for** the `gatsby-config`.

The `gatsby-browser` and `gatsby-ssr` processing doesn't happen till much later, after Gatsby's bootstrap is done, so it shouldn't affect your bootstrap phase  **at all** (especially not the `open and validate gatsby-configs` stage).  However, even though Gatsby uses Webpack for bundling the site, I still make sure to limit the scope of this plugin to **only** processing `gatsby-config` and `gatsby-node`.  If it is bleeding over, then it is a bug, and should be worked out instead of worked around.

I'm all for exposing an `ignore` hook, so I will implement that probably later today.  However, it is also important to make sure that this isn't a bug.  To that end, an example repo would be very helpful.

**Comment by Js-Brecht** [comment] 2020-04-23 19:44
@flogy I've implemented an ignore hook.  Please check out #9 if you're interested in how it's done.  I've published the change as `gatsby-plugin-ts-config@next`.  You can see the documentation [here](https://github.com/Js-Brecht/gatsby-plugin-ts-config/blob/6f316d188563b86ca8bb1f71d1f771f3ea542949/README.md#plugin-options)

**Comment by flogy** [comment] 2020-04-24 12:46
@Js-Brecht Woah, thank you so much! I just tested it and could get it to work now! 🎉

However, it is a bit weird, because it works fine when I just include the default ignore hook like this:

```javascript
module.exports = {
  plugins: [
    {
      resolve: `gatsby-plugin-ts-config`,
      options: {
        configDir: "src/gatsby",
        hooks: {
          ignore: (filename, getDefault) => {}
        }
      }
    }
  ]
};
```

But not when I don't explicitly include the hook:

```javascript
module.exports = {
  plugins: [
    {
      resolve: `gatsby-plugin-ts-config`,
      options: {
        configDir: "src/gatsby"
      }
    }
  ]
};
```

**Comment by Js-Brecht** [comment] 2020-04-24 15:44
I rethought the hook parameters shortly after I left that comment, to make consumption a bit simpler.  I had updated the documentation, but I forgot to update the link in my last comment.  [Here is the updated version](https://github.com/Js-Brecht/gatsby-plugin-ts-config/blob/04711c7c9a9639cfe2508790dc3c0d1ad8aaf77b/README.md#plugin-options).  Basically, that second parameter will just be a Boolean, instead of a function.  There was no need to have the user call a function to get the default ignore value, when it could be checked ahead of time.

The updated doc should explain why it’s working like you are using it.  If you don’t return a value from your hook, it is basically returning `void`, which is a false value.  That’s telling the transpiler not to ignore anything.  The reason it ignores anything to begin with is to improve performance.  It’s really up to you whether that matters to you; in your case, it might be processing so little that it doesn’t matter.

I still need to see an example of this in action, if you don’t mind.  It seems really strange to me that this process would have any affect on `gatsby-browser`/`gatsby-ssr`.

**Comment by Js-Brecht** [comment] 2020-04-24 16:17
I changed the hook behavior to be more consistent.

You won't receive a value in the second parameter anymore, because it won't be needed.  If you return anything but a boolean value from the hook, it will use the default procedure.

Now, if you don't do anything in the hook, it will just use the default ignore values.  If you return `true`, it will not process the file.  If you return `false`, it will process the file.

**Comment by flogy** [comment] 2020-04-28 07:02
Hi @Js-Brecht 

Thank you for your efforts!

I could now find the **real** problem causing this. It was *not* because of the wrapped root component, where the Wrapper is importing `capacitor-fcm`! It was because I was also importing a constant into my `gatsby-config.ts` file. That constant was exported from a TS file that over several dependencies also imported `capacitor-fcm`. I'm sorry for overlooking this important information!

So I could solve it by just moving the constant out of that TS file into a separate one which is not importing anything that could be related to `capacitor-fcm`.

I have now also created a [sample repository](https://github.com/flogy/gatsby-plugin-ts-config-es6-issue) which reproduces the issue. See [this commit](https://github.com/flogy/gatsby-plugin-ts-config-es6-issue/commit/1ad4a4f06b4b6e41e5778e153ce6e9eaa72d1ff3) to check out what I am talking about.

I was not able to fix resolve this issue by ignoring the `capacitor-fcm` using your hook 🤔

**Comment by Js-Brecht** [comment] 2020-04-29 00:36
> I could now find the **real** problem causing this. It was _not_ because of the wrapped root component, where the Wrapper is importing `capacitor-fcm`! It was because I was also importing a constant into my `gatsby-config.ts` file. That constant was exported from a TS file that over several dependencies also imported `capacitor-fcm`. I'm sorry for overlooking this important information!

Ahh, that makes sense.

> I was not able to fix resolve this issue by ignoring the `capacitor-fcm` using your hook 🤔

You would actually have to tell the transpiler _**not**_ to ignore it.  Probably something like this:

```js
ignore: (filename) => {
  if (/[/\\]capacitor-fcm[/\\]/i.test(filename)) {
    return false;
  }
}
```

If the name contains `capacitor-fcm` as a folder name, then it will _**not**_ ignore it.  If the current filename doesn't match the pattern, then nothing gets returned from the function, which makes it use the default behavior.  Could even do `return;` or `return null;`, etc... as long as it's not a `true` or ` false`.

---

I'm going to go ahead and close this issue now, because it seems as though it's been resolved.  If you have further feedback or questions, please feel free to comment!

**Closed by Js-Brecht** 2020-04-29 00:36 UTC
Labels: bug, enhancement, needs reproduction

**Comment by balibebas** [comment] 2020-07-14 08:36
I ran into a similar issue with `gatsby-theme-shopify-manager`. The issue was caused in my `gatsby-node` file when I attempted to include a template file for `createPages` programmatic page creation on an exsiting site I was trying this out on. I did not debug further. Here's the error:

```term
[gatsby-plugin-ts-config] An error occurred while reading your gatsby-node!
Unexpected token 'export'

  Error: /home/bali/Developer/jamupuri-website/node_modules/gatsby-theme-shopif  y-manager/index.js:1
  (function (exports, require, module, __filename, __dirname) { export * from '  ./src';
                                                                ^^^^^^
  SyntaxError: Unexpected token 'export'
```

**Comment by Js-Brecht** [comment] 2020-07-14 15:38
@balibebas it sounds like you tried to `require` the module, while `createPages()` needs a path to the file.

If that’s off the mark, then it would help a great deal if I could see the code

**Comment by balibebas** [comment] 2020-07-14 20:53
Hey Jeremy. This particular source I've closed. It builds off a TypeScript starter I created, however. I'll spend some time trying to produce a minimal test case for you after some sleep. I don't want to get too deep in the weeds though as I'm trying to focus on higher value tasks.

**Comment by balibebas** [comment] 2020-07-14 20:55
Hey Jeremy. This particular source I've closed. It builds off a TypeScript starter I created, however. I'll spend some time trying to produce a minimal test case for you after some sleep. I don't want to get too deep in the weeds though as I'm trying to focus on high value tasks.

**Comment by balibebas** [comment] 2020-07-14 21:59
https://git.habd.as/comfusion/gatsby-starter-i18n-react-i18next/src/branch/repro/ts-config-import-issue

I wasn't able to repro the issue mentioned in my reduced test case but this code does create some issues using the plugin mentioned in combination with a ts config. Please see diff of most recent commit in branch linked above. There's some code in `gatsby-node.ts` doing the import which caused the issue in my closed code but I didn't get so far as to reproduce the problem before I hit a different issue integrating. Maybe it'll be helpful for debugging or design given it's a more _in-the-wild_ type use case. I'll leave the branch around for awhile in case it can be helpful for debugging @Js-Brecht.

**Comment by Js-Brecht** [comment] 2020-07-14 23:43
Hey @balibebas, thanks for the repro!  I sent you a message on gitter, but I also wanted to address the issue I see here

I assume that the commented lines in `gatsby-node` are what were breaking? I was able to get it working with this:

```diff
-   import Product from "../src/templates/product";

....

    createPage({
      path: `/product/${node.handle}/`,
-     component: Product,
+     component: require.resolve('../src/templates/product'),
      context: {
        handle: node.handle,
      },
    });
```

The `component` prop on `createPage()` needs to the path to the component to load, not the component itself.

The main issue with importing components in `gatsby-node` that are meant to be used during run time is that they are meant to run in the browser; `gatsby-node` is being run during build time, so it is only running in Node.  Since those run time modules need to run in the browser, they are built with Webpack, and there's a lot more going on there than what can comfortably done from `gatsby-plugin-ts-config` in order to make them (reliably) consumable in Node.

**Comment by balibebas** [comment] 2020-07-15 06:14
Well don't I feel stupid. :smile: You were right. I tried this out on my actual project and the entire project including auth worked without a hitch. I've restored your plugin to my starter in case anyone wants to see a sample integration:

https://git.habd.as/comfusion/gatsby-starter-i18n-react-i18next/

Thanks again for your help.
